version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: minha_loja_api_development
    ports:
      # CORREÇÃO: Mapeia para a porta 3307 do host para evitar conflito.
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/minha_loja_api
    depends_on:
      - db
    environment:
      # O HOST do banco de dados ainda é 'db', o nome do serviço no Docker Compose.
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: 123
      
volumes:
  db_data: